### ISSUE TITLE
Demos do not work

### ISSUE THREAD

**Issue by TimMurphy** [jrsearles/Elmah.AspNetCore#75]
Each of the 3 demo project produces the same error.

When the demo is started the index/home page deliberately throws a divide by exception but the result in the browser is:

```
https://localhost:7295/elmah.axd/detail/{error id}
```

The error is logged to the console window and is:

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.DivideByZeroException: Attempted to divide by zero.
         at Elmah.AspNetCore.DemoCore8.Pages.IndexModel.OnGetAsync() in D:\Code\Clones\Elmah.AspNetCore\demos\Elmah.AspNetCore.DemoCore8\Pages\Index.cshtml.cs:line 28
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.NonGenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Elmah.AspNetCore.ErrorLogMiddleware.ExecuteMiddlewareAsync(HttpContext context) in D:\Code\Clones\Elmah.AspNetCore\src\Elmah.AspNetCore\ErrorLogMiddleware.cs:line 100
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Elmah.AspNetCore[0]
      index.html is not found for Elmah - has static content been generated?
```

If I replace the project reference with the current NuGet package the demo works.

**Comment by jrsearles** [comment]
Sorry I missed this. You need to generate the static content. I added a section to the README for running locally and updated error to be a little clearer.
